import { config } from './config.js';

// Generated by tests/load/generate-k6-endpoints.mjs from an OpenAPI document.
function root() {
  return [config.baseUrl, config.apiPrefix, config.procSchema]
    .filter(Boolean)
    .join('/');
}

function withQuery(path, params) {
  const query = Object.entries(params)
    .filter(([, value]) => value !== '' && value !== undefined && value !== null)
    .map(([key, value]) => `${encodeURIComponent(key)}=${encodeURIComponent(String(value))}`)
    .join('&');

  return query ? `${path}?${query}` : path;
}

export function companies(page = 1, pageSize = 25, search = '') {
  const firstRow = Math.max(0, (page - 1) * pageSize);
  const lastRow = firstRow + pageSize;
  return withQuery(`${root()}/companies`, {
    first_row: firstRow,
    last_row: lastRow,
  filter: search,
  });
}
export function company(id = config.defaultCompanyId) {
  return withQuery(`${root()}/companies`, { "ID": id });
}
export function createCompany(params = {}) {
  return withQuery(`${root()}/companies`, { "name": params["name"], "sector": params["sector"], "size": params["size"], "linkedin_url": params["linkedin_url"], "website": params["website"], "phone_number": params["phone_number"], "address": params["address"], "zipcode": params["zipcode"], "city": params["city"], "state_abbr": params["state_abbr"], "country": params["country"], "description": params["description"], "revenue": params["revenue"], "tax_identifier": params["tax_identifier"], "created_at": params["created_at"], "sales_id": params["sales_id"], "logo_src": params["logo_src"], "logo_title": params["logo_title"], "logo_path": params["logo_path"], "logo_type": params["logo_type"], "context_links": params["context_links"] });
}
export function updateCompany(params = {}) {
  return withQuery(`${root()}/companies`, { "ID": params["ID"], "name": params["name"], "sector": params["sector"], "size": params["size"], "linkedin_url": params["linkedin_url"], "website": params["website"], "phone_number": params["phone_number"], "address": params["address"], "zipcode": params["zipcode"], "city": params["city"], "state_abbr": params["state_abbr"], "country": params["country"], "description": params["description"], "revenue": params["revenue"], "tax_identifier": params["tax_identifier"], "created_at": params["created_at"], "sales_id": params["sales_id"], "logo": params["logo"], "context_links": params["context_links"] });
}
export function deleteCompany(id) {
  return withQuery(`${root()}/companies`, { "ID": id });
}
export function companiesSummary(page = 1, pageSize = 25, search = '') {
  const firstRow = Math.max(0, (page - 1) * pageSize);
  const lastRow = firstRow + pageSize;
  return withQuery(`${root()}/companies_summary`, {
    first_row: firstRow,
    last_row: lastRow,
  filter: search,
  });
}
export function configuration(params = {}) {
  return withQuery(`${root()}/configuration`, { "ID": params["ID"] });
}
export function updateConfiguration(params = {}) {
  return withQuery(`${root()}/configuration`, { "ID": params["ID"], "config": params["config"] });
}
export function contactNotes(page = 1, pageSize = 25, search = '') {
  const firstRow = Math.max(0, (page - 1) * pageSize);
  const lastRow = firstRow + pageSize;
  return withQuery(`${root()}/contact_notes`, {
    first_row: firstRow,
    last_row: lastRow,
  filter: search,
  });
}
export function contactNote(id = config.defaultContactNoteId) {
  return withQuery(`${root()}/contact_notes`, { "ID": id });
}
export function createContactNote(params = {}) {
  return withQuery(`${root()}/contact_notes`, { "contact_id": params["contact_id"], "sales_id": params["sales_id"], "date": params["date"], "text": params["text"], "status": params["status"], "attachments": params["attachments"] });
}
export function updateContactNote(params = {}) {
  return withQuery(`${root()}/contact_notes`, { "ID": params["ID"], "contact_id": params["contact_id"], "sales_id": params["sales_id"], "date": params["date"], "text": params["text"], "status": params["status"], "attachments": params["attachments"] });
}
export function deleteContactNote(id) {
  return withQuery(`${root()}/contact_notes`, { "ID": id });
}
export function contacts(page = 1, pageSize = 25, search = '') {
  const firstRow = Math.max(0, (page - 1) * pageSize);
  const lastRow = firstRow + pageSize;
  return withQuery(`${root()}/contacts`, {
    first_row: firstRow,
    last_row: lastRow,
  filter: search,
  });
}
export function contact(id = config.defaultContactId) {
  return withQuery(`${root()}/contacts`, { "ID": id });
}
export function createContact(params = {}) {
  return withQuery(`${root()}/contacts`, { "first_name": params["first_name"], "last_name": params["last_name"], "title": params["title"], "company_id": params["company_id"], "sales_id": params["sales_id"], "linkedin_url": params["linkedin_url"], "first_seen": params["first_seen"], "last_seen": params["last_seen"], "has_newsletter": params["has_newsletter"], "gender": params["gender"], "status": params["status"], "background": params["background"], "emails_jsonb": params["emails_jsonb"], "phones_jsonb": params["phones_jsonb"], "avatar_src": params["avatar_src"], "avatar_title": params["avatar_title"], "avatar_path": params["avatar_path"], "avatar_type": params["avatar_type"] });
}
export function updateContact(params = {}) {
  return withQuery(`${root()}/contacts`, { "ID": params["ID"], "first_name": params["first_name"], "last_name": params["last_name"], "title": params["title"], "company_id": params["company_id"], "sales_id": params["sales_id"], "linkedin_url": params["linkedin_url"], "first_seen": params["first_seen"], "last_seen": params["last_seen"], "has_newsletter": params["has_newsletter"], "gender": params["gender"], "status": params["status"], "background": params["background"], "email_jsonb": params["email_jsonb"], "phone_jsonb": params["phone_jsonb"], "avatar_src": params["avatar_src"], "avatar_title": params["avatar_title"], "avatar_path": params["avatar_path"], "avatar_type": params["avatar_type"], "tags": params["tags"] });
}
export function contactsSummary(page = 1, pageSize = 25, search = '') {
  const firstRow = Math.max(0, (page - 1) * pageSize);
  const lastRow = firstRow + pageSize;
  return withQuery(`${root()}/contacts_summary`, {
    first_row: firstRow,
    last_row: lastRow,
  filter: search,
  });
}
export function dealNotes(page = 1, pageSize = 25, search = '') {
  const firstRow = Math.max(0, (page - 1) * pageSize);
  const lastRow = firstRow + pageSize;
  return withQuery(`${root()}/deal_notes`, {
    first_row: firstRow,
    last_row: lastRow,
  filter: search,
  });
}
export function dealNote(id = config.defaultDealNoteId) {
  return withQuery(`${root()}/deal_notes`, { "ID": id });
}
export function createDealNote(params = {}) {
  return withQuery(`${root()}/deal_notes`, { "deal_id": params["deal_id"], "sales_id": params["sales_id"], "date": params["date"], "text": params["text"], "attachments": params["attachments"] });
}
export function updateDealNote(params = {}) {
  return withQuery(`${root()}/deal_notes`, { "ID": params["ID"], "deal_id": params["deal_id"], "sales_id": params["sales_id"], "date": params["date"], "text": params["text"], "attachments": params["attachments"] });
}
export function deleteDealNote(id) {
  return withQuery(`${root()}/deal_notes`, { "ID": id });
}
export function deals(page = 1, pageSize = 25, search = '') {
  const firstRow = Math.max(0, (page - 1) * pageSize);
  const lastRow = firstRow + pageSize;
  return withQuery(`${root()}/deals`, {
    first_row: firstRow,
    last_row: lastRow,
  filter: search,
  });
}
export function deal(id = config.defaultDealId) {
  return withQuery(`${root()}/deals`, { "ID": id });
}
export function createDeal(params = {}) {
  return withQuery(`${root()}/deals`, { "name": params["name"], "company_id": params["company_id"], "category": params["category"], "stage": params["stage"], "description": params["description"], "amount": params["amount"], "expected_closing_date": params["expected_closing_date"], "sales_id": params["sales_id"], "index": params["index"] });
}
export function updateDeal(params = {}) {
  return withQuery(`${root()}/deals`, { "ID": params["ID"], "name": params["name"], "company_id": params["company_id"], "category": params["category"], "stage": params["stage"], "description": params["description"], "amount": params["amount"], "expected_closing_date": params["expected_closing_date"], "sales_id": params["sales_id"], "index": params["index"] });
}
export function createLogin(params = {}) {
  return withQuery(`${root()}/login`, { "username": params["username"], "passwordHash": params["passwordHash"] });
}
export function objects(params = {}) {
  return withQuery(`${root()}/objects`, { "id": params["id"], "object_path": params["object_path"] });
}
export function object(id = config.defaultObjectId) {
  return withQuery(`${root()}/objects`, { "id": id });
}
export function createObject(params = {}) {
  return withQuery(`${root()}/objects`, { "bucket_id": params["bucket_id"], "object_path": params["object_path"], "content_type": params["content_type"], "sha256_hex": params["sha256_hex"], "data": params["data"] });
}
export function sales(page = 1, pageSize = 25, search = '') {
  const firstRow = Math.max(0, (page - 1) * pageSize);
  const lastRow = firstRow + pageSize;
  return withQuery(`${root()}/sales`, {
    first_row: firstRow,
    last_row: lastRow,
  filter: search,
  });
}
export function sale(id = config.defaultSaleId) {
  return withQuery(`${root()}/sales`, { "ID": id });
}
export function createSale(params = {}) {
  return withQuery(`${root()}/sales`, { "user_id": params["user_id"], "email": params["email"], "first_name": params["first_name"], "last_name": params["last_name"], "administrator": params["administrator"], "disabled": params["disabled"], "avatar_src": params["avatar_src"], "avatar_title": params["avatar_title"], "avatar_path": params["avatar_path"], "avatar_type": params["avatar_type"] });
}
export function updateSale(params = {}) {
  return withQuery(`${root()}/sales`, { "ID": params["ID"], "email": params["email"], "first_name": params["first_name"], "last_name": params["last_name"], "administrator": params["administrator"], "disabled": params["disabled"], "avatar": params["avatar"] });
}
export function updateSalesPassword(params = {}) {
  return withQuery(`${root()}/sales_password`, { "id": params["id"], "passwordHash": params["passwordHash"] });
}
export function tags(page = 1, pageSize = 25, search = '') {
  const firstRow = Math.max(0, (page - 1) * pageSize);
  const lastRow = firstRow + pageSize;
  return withQuery(`${root()}/tags`, {
    first_row: firstRow,
    last_row: lastRow,
  filter: search,
  });
}
export function tag(id = config.defaultTagId) {
  return withQuery(`${root()}/tags`, { "ID": id });
}
export function createTag(params = {}) {
  return withQuery(`${root()}/tags`, { "name": params["name"], "color": params["color"] });
}
export function tasks(page = 1, pageSize = 25, search = '') {
  const firstRow = Math.max(0, (page - 1) * pageSize);
  const lastRow = firstRow + pageSize;
  return withQuery(`${root()}/tasks`, {
    first_row: firstRow,
    last_row: lastRow,
  filter: search,
  });
}
export function task(id = config.defaultTaskId) {
  return withQuery(`${root()}/tasks`, { "ID": id });
}
export function createTask(params = {}) {
  return withQuery(`${root()}/tasks`, { "contact_id": params["contact_id"], "sales_id": params["sales_id"], "type": params["type"], "text": params["text"], "due_date": params["due_date"], "done_date": params["done_date"] });
}
export function updateTask(params = {}) {
  return withQuery(`${root()}/tasks`, { "ID": params["ID"], "contact_id": params["contact_id"], "sales_id": params["sales_id"], "type": params["type"], "text": params["text"], "due_date": params["due_date"], "done_date": params["done_date"] });
}

export const customerList = contacts;
export const customerGet = contact;
export function orderCreate() {
  return `${root()}/OrderCreate`;
}

export function healthPing() {
  return `${config.baseUrl}/../../ping`;
}
